string strGrade3 = "\t1 => AGRICULTURE GRADE 3 TEST 1\n\n\t2 => AGRICULTURE GRADE 3 TEST 2\n\n\t3 => AGRICULTURE GRADE 3 TEST 3\n\n\t4 => AGRICULTURE GRADE 3 TEST 4\n\n";

string strGrade4 = "\t1 => AGRICULTURE GRADE 4 TEST 1\n\n\t2 => AGRICULTURE GRADE 4 TEST 2\n\n\t3 => AGRICULTURE GRADE 4 TEST 3\n\n\t4 => AGRICULTURE GRADE 4 TEST 4\n\n";

string strGrade5 = "\t1 => AGRICULTURE GRADE 5 TEST 1\n\n\t2 => AGRICULTURE GRADE 5 TEST 2\n\n\t3 => AGRICULTURE GRADE 5 TEST 3\n\n\t4 => AGRICULTURE GRADE 5 TEST 4\n\n";

string strGrade6 = "\t1 => AGRICULTURE GRADE 6 TEST 1\n\n\t2 => AGRICULTURE GRADE 6 TEST 2\n\n\t3 => AGRICULTURE GRADE 6 TEST 3\n\n\t4 => AGRICULTURE GRADE 6 TEST 4\n\n";

string strGrade7 = "\t1 => AGRICULTURE GRADE 7 TEST 1\n\n\t2 => AGRICULTURE GRADE 7 TEST 2\n\n\t3 => AGRICULTURE GRADE 7 TEST 3\n\n\t4 => AGRICULTURE GRADE 7 TEST 4\n\n";

string strBITH = "\t1 => HTML TEST 1\n\n\t2 => CCNA TEST 1\n\n\t3 => CCNA TEST 2\n\n\t4 => CCNA TEST 3\n\n";
